pipeline {
    agent { label 'Salimli' }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '10'))
        disableConcurrentBuilds()
    }

    stages {
        stage('Build JAR') {
            steps {
                dir('TripPlannerBot') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean shadowJar --no-daemon'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'TripPlannerBot/build/libs/*.jar', fingerprint: true, allowEmptyArchive: true
        }
    }
}
